### ISSUE TITLE
Idea [Running TFC on three Qubes VMs on a single device]

### ISSUE THREAD

**Issue by PowerPress** [maqp/tfc#3] opened 2018-04-26 21:01 UTC
Have you considered the idea of creating away to use this with Qubes separate VMs to replace the hardware components? You could get much more adoption with the goal of strong isolation at the cost of some security you would have from the physical diodes. They already have Whonix based support and I think their user base would like this.

**Comment by maqp** [comment] 2018-04-27 01:26
Yes, I've considered that and I see the benefits. Alas, my HW is either too old or new to run Qubes, so it's not possible to even play around with the OS. I'm not sure if Qubes allows unidirectional data transmission across VMs so that needs to be confirmed as well. I'll probably start looking into this once TFC and its protocol feel more complete and once Qubes supports my HW.

**Comment by PowerPress** [comment] 2018-04-27 01:35
Awesome. FYI you can virtualize Qubes to test your code and etc. It will
run for development purposes. The VMs have their own firewall with complete
rules over every aspect seems perfect for your solution to security via
compartmentalization.

**Comment by maqp** [comment] 2020-02-16 23:44
I'm not able to dedicate much of my time to this ticket (since I'm quite busy with my personal life), but I've finally kicked it off. Twitter discussion [here](https://twitter.com/InfoSecZ/status/1174325406088015873).

**Comment by maqp** [comment] 2020-02-23 03:42
I played around a bit and got TFC working with Qubes 4:
![](https://i.imgur.com/5jJ5Hpx.png)

Some observations
* The installer has issues with torsocks. The three Debian 10 standalone VMs need to use the Whonix gateway -- something the users need to do themselves.
* Effective TCB isolation from network needs to be done manually by the user after the TCB configuration has been installed (Qube setting for `Networking` needs to be set to `(none)`).
* Unidirectional communication currently works only through the data diode. The adapters need to be connected one by one, and assigned manually to the proper VM. This needs to be done every time the VM is restarted (pinning device might be possible).
* I need to figure out how to transfer data between VMs without the data diodes (sockets, firewall rules etc.) Initially I considered writing the ciphertext to file and using `qvm-move`, but since the "approve for subsequent transfers" options has been deprecated, this requires manual approval of every CT transferred and is thus not usable in any way.
* I need to figure out how much of the TFC launcher creation (if possible) can be automated (considering that happens in `dom0` that might not be possible), or whether TFC needs to be started from the VM's terminal every time.

**Comment by maqp** [comment] 2020-03-06 15:47
@PowerPress TFC 1.19.03 Is now released with support for Qubes. Closing. :tada:

**Closed by maqp** 2020-03-06 15:47 UTC
