### ISSUE TITLE
Running Python with optimizations enabled strips assertions

### ISSUE THREAD

**Issue by zoresvit** [maqp/tfc#4] opened 2019-01-29 00:04 UTC
Just wanted to point out that if Python is run with `-O` (optimize) option, it will strip all `assert` statements and these checks will effectively disappear:

https://github.com/maqp/tfc/blob/033ee0899b35c2f0407e3819965821c74e92716f/src/common/crypto.py#L156

You can read about it more in [Python docs](https://wiki.python.org/moin/UsingAssertionsEffectively).

TL;DR:

> Assertions should *not* be used to test for failure cases that can occur because of bad user input or operating system/environment failures, such as a file not being found. Instead, you should raise an exception, or print an error message, or whatever is appropriate. One important reason why assertions should only be used for self-tests of the program is that assertions can be disabled at compile time.
> If Python is started with the -O option, then assertions will be stripped out and not evaluated.

It might still be okay, depending on what the intent is, just wanted to make sure you're aware of this nuance.

PS: Thanks for posting about your work in ModernCrypto mailing list 👍

**Comment by maqp** [comment] 2019-01-29 02:20
The TFC launchers don't use the -O option, so there's no immediate danger in the intended behavior. However, you are right, I should change asserts to conditional expressions. This will be fixed in the next release.

**Comment by maqp** [comment] 2019-03-03 10:27
The 1.19.03 no longer uses asserts. Closing.

**Closed by maqp** 2019-03-03 10:27 UTC
